# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/FeryET/pre-commit-rust
    rev: v1.1.1
    hooks:
        - id: fmt
        - id: cargo-check
        - id: clippy
