name: Publish Binaries

on:
  release:
    types: [published]

jobs:
  build-and-attach:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl, aarch64-unknown-linux-gnu, aarch64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@v3

      - name: Install targets
        run: |
          rustup target add ${{ matrix.platform }}

      - name: Build
        run: |
          cargo build --release --target ${{ matrix.platform }}
      
      - name: Upload as release asset
        uses: softprops/action-gh-release@v1
        with:
          # Attach to the existing release identified by the tag
          tag_name: ${{ github.event.release.tag_name }}
          files: target/${{ matrix.platform }}/release/cephdu
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
